export type Coin = {
  externalId?: string;
  rank: number;
  name: string;
  symbol: string;
  chain: string;
  logo: string;
  image?: string;
  color: string;
  cap: string;
  capN: number;
  price: string;
  change: number;
  launch: string;
  boost?: number;
  votes: number;
  age: string;
  category: string;
  trend: number;
  contractAddress?: string;
  buyUrl?: string;
};

export type SortKey =
  'rank' | 'name' | 'capN' | 'price' | 'change' | 'launch' | 'boost' | 'votes' | 'age';

export const featuredCoins: Coin[] = [
  {
    rank: 1,
    name: 'NeuroMesh',
    symbol: 'NMESH',
    chain: 'SOL',
    logo: 'N',
    color: 'violet',
    cap: '$18.4M',
    capN: 18.4,
    price: '$0.0482',
    change: 28.4,
    launch: 'Aug 21',
    boost: 500,
    votes: 18420,
    age: '5d ago',
    category: 'AI',
    trend: 98,
  },
  {
    rank: 2,
    name: 'Based Pepe',
    symbol: 'BPEPE',
    chain: 'BASE',
    logo: 'B',
    color: 'cyan',
    cap: '$6.7M',
    capN: 6.7,
    price: '$0.00084',
    change: 12.7,
    launch: 'Aug 18',
    boost: 100,
    votes: 12790,
    age: '8d ago',
    category: 'Memecoins',
    trend: 91,
  },
  {
    rank: 3,
    name: 'VaultFi',
    symbol: 'VFI',
    chain: 'ETH',
    logo: 'V',
    color: 'orange',
    cap: '$42.1M',
    capN: 42.1,
    price: '$1.284',
    change: -3.2,
    launch: 'Jul 30',
    boost: 50,
    votes: 11326,
    age: '27d ago',
    category: 'DeFi',
    trend: 85,
  },
  {
    rank: 4,
    name: 'Pixel Pals',
    symbol: 'PXP',
    chain: 'MATIC',
    logo: 'P',
    color: 'pink',
    cap: '$3.2M',
    capN: 3.2,
    price: '$0.0215',
    change: 8.9,
    launch: 'Aug 23',
    boost: 30,
    votes: 9814,
    age: '3d ago',
    category: 'Gaming',
    trend: 81,
  },
  {
    rank: 5,
    name: 'SuiPilot',
    symbol: 'PILOT',
    chain: 'SUI',
    logo: 'S',
    color: 'blue',
    cap: '$11.8M',
    capN: 11.8,
    price: '$0.173',
    change: 4.1,
    launch: 'Aug 11',
    boost: 10,
    votes: 8202,
    age: '15d ago',
    category: 'Utility Token',
    trend: 77,
  },
  {
    rank: 6,
    name: 'Arcadia',
    symbol: 'ARCA',
    chain: 'ARB',
    logo: 'A',
    color: 'green',
    cap: '$27.6M',
    capN: 27.6,
    price: '$0.392',
    change: 16.2,
    launch: 'Aug 20',
    votes: 7345,
    age: '6d ago',
    category: 'Play To Earn',
    trend: 73,
  },
  {
    rank: 7,
    name: 'Degen Doge',
    symbol: 'DDOGE',
    chain: 'BSC',
    logo: 'D',
    color: 'yellow',
    cap: '$2.9M',
    capN: 2.9,
    price: '$0.000031',
    change: -6.8,
    launch: 'Aug 24',
    votes: 6891,
    age: '2d ago',
    category: 'Memecoins',
    trend: 68,
  },
  {
    rank: 8,
    name: 'FanForge',
    symbol: 'FORGE',
    chain: 'AVAX',
    logo: 'F',
    color: 'red',
    cap: '$8.1M',
    capN: 8.1,
    price: '$0.094',
    change: 2.3,
    launch: 'Aug 09',
    votes: 5744,
    age: '17d ago',
    category: 'Fan Token',
    trend: 62,
  },
];

const generatedNames = [
  'Moon Casino',
  'NovaNFT',
  'PumpKit',
  'TronSpark',
  'MetaMint',
  'GameGrid',
  'YieldNest',
  'Ape Arena',
  'XRPulse',
  'Fantom Fox',
  'MemePilot',
  'ChainClub',
  'LuckyBlock',
  'RWA Core',
  'SolQuest',
  'BaseByte',
  'DogeTools',
  'SuiVerse',
  'Opal AI',
  'KCC Labs',
  'AvalancheX',
  'EtherFan',
];
const generatedCategories = [
  'Gambling',
  'NFT Platform',
  'Pump.fun Tokens',
  'Other',
  'Utility Token',
  'Gaming',
  'DeFi',
  'Play To Earn',
  'Other',
  'Memecoins',
  'Pump.fun Tokens',
  'Fan Token',
  'Gambling',
  'DeFi',
  'Gaming',
  'Utility Token',
  'Other',
  'NFT Platform',
  'AI',
  'Other',
  'DeFi',
  'Fan Token',
];
const generatedChains = [
  'SOL',
  'ETH',
  'BSC',
  'TRX',
  'BASE',
  'MATIC',
  'ARB',
  'SUI',
  'XRPL',
  'FTM',
  'OP',
  'KCC',
  'AVAX',
  'DOGE',
];
const logoColors = ['violet', 'cyan', 'orange', 'pink', 'blue', 'green', 'yellow', 'red'];

export const coins: Coin[] = [
  ...featuredCoins,
  ...generatedNames.map((name, index) => ({
    rank: index + 9,
    name,
    symbol: name
      .replace(/[^A-Z]/gi, '')
      .slice(0, 5)
      .toUpperCase(),
    chain: generatedChains[index % generatedChains.length],
    logo: name[0],
    color: logoColors[index % logoColors.length],
    cap: `$${(1.4 + index * 1.9).toFixed(1)}M`,
    capN: 1.4 + index * 1.9,
    price: `$0.${String(172 + index * 37).padStart(4, '0')}`,
    change: +((index % 3 === 0 ? -1 : 1) * (2.1 + index * 0.7)).toFixed(1),
    launch: `Aug ${String(1 + (index % 25)).padStart(2, '0')}`,
    votes: 5200 - index * 137,
    age: `${index + 3}d ago`,
    category: generatedCategories[index],
    trend: 60 - index,
  })),
];

export const categories = [
  'All',
  'AI',
  'DeFi',
  'Fan Token',
  'Gambling',
  'Gaming',
  'Memecoins',
  'NFT Platform',
  'Other',
  'Play To Earn',
  'Pump.fun Tokens',
  'Utility Token',
];
export const chainOptions = [
  'All chains',
  'ETH',
  'BSC',
  'SOL',
  'MATIC',
  'AVAX',
  'ARB',
  'BASE',
  'OP',
  'DOGE',
  'TRX',
  'FTM',
  'KCC',
  'SUI',
  'HOOD',
  'XRPL',
  'OTHER',
];
export const formatVotes = (value: number) => new Intl.NumberFormat('en-US').format(value);
